# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Find your next job in data science in the Federal Government
email: matthew.dingee@opm.gov
description: >
  Find out what it takes to have a career in data science within the Federal Government
logo: "/assets/images/logo-2x.png"
url: "http://usajobs.github.io/microsite-data-science/" # the base hostname & protocol for your site

exclude:
- Gemfile
- Gemfile.lock
- Gruntfile.js
- package.json
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- npm-debug.log
- node_modules

baseurl: '/microsite-data-science'
destination: ./_dist

author:
  name: USAJOBS
  url: https://usajobs.github.io/

repository:
  name: microsite-data-science
  url: https://github.com/USAJOBS/microsite-data-science/

# Google Analytics
analytics_id: "UA-33523145-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  pages:
    output: true
    permalink: /:path/
